<a href="https://colab.research.google.com/github/Noma9d/Python_Data_Science/blob/main/Hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 6  2  8  1  5]
 [ 1  6 10  1  2]
 [10  2  6  3  1]
 [ 9 10  8  6  8]
 [ 3  4  5  2  5]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
zero_to_one_random_matrix = np.random.rand(4, 4)
print(zero_to_one_random_matrix)

[[0.53418987 0.23603448 0.0045276  0.64193543]
 [0.35993894 0.69539984 0.75562775 0.62554269]
 [0.7472758  0.30028733 0.48292094 0.89618091]
 [0.0121684  0.59742635 0.88575877 0.70719907]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.



In [ ]:
first_matrix = np.random.randint(1, 11, size=5)
second_matrix = np.random.randint(1, 11, size=5)

res_add = first_matrix + second_matrix
res_sub = first_matrix - second_matrix
res_mul = first_matrix * second_matrix

print('first_matrix:',first_matrix)
print('second_matrix:',second_matrix)

print('res_add:',res_add)
print('res_sub:',res_sub)
print('res_mul:',res_mul)

first_matrix: [5 9 4 3 7]
second_matrix: [3 8 9 7 4]
res_add: [ 8 17 13 10 11]
res_sub: [ 2  1 -5 -4  3]
res_mul: [15 72 36 21 28]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([8, 9, 10, 11, 12, 13, 14])

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
scalar_product = np.dot(vector1, vector2)
print('scalar_product:', scalar_product)

Вектор 1: [1 2 3 4 5 6 7]
Вектор 2: [ 8  9 10 11 12 13 14]
scalar_product: 336


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("Результат перемноження матриць:")
print(result)

Матриця 1:
[[6 4]
 [4 2]]
Матриця 2:
[[ 8 10  7]
 [ 9  6  8]]
Результат перемноження матриць:
[[84 84 74]
 [50 52 44]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 11, size=(3, 3))

print("Матриця:")
print(matrix)
inverse_matrix = np.linalg.inv(matrix)

print("Обернена матриця:")
print(inverse_matrix)

Матриця:
[[ 7  4  3]
 [10  2  4]
 [ 5  1  7]]
Обернена матриця:
[[-0.07692308  0.19230769 -0.07692308]
 [ 0.38461538 -0.26153846 -0.01538462]
 [ 0.         -0.1         0.2       ]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix = np.random.rand(4, 4)

print("Матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)

Матриця:
[[0.61314267 0.57673974 0.06875511 0.40347165]
 [0.62265303 0.48977848 0.46560409 0.14365297]
 [0.77825118 0.14767831 0.09644416 0.32646552]
 [0.64648268 0.32129656 0.31562741 0.96593364]]
Транспонована матриця:
[[0.61314267 0.62265303 0.77825118 0.64648268]
 [0.57673974 0.48977848 0.14767831 0.32129656]
 [0.06875511 0.46560409 0.09644416 0.31562741]
 [0.40347165 0.14365297 0.32646552 0.96593364]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження матриці на вектор:")
print(result)

Матриця:
[[8 9 7 2]
 [9 8 3 2]
 [4 2 6 9]]
Вектор:
[8 6 3 3]
Результат перемноження матриці на вектор:
[145 135  89]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

result = np.dot(matrix, vector)

print("Результат перемноження матриці на вектор:")
print(result)

Матриця:
[[0.54118999 0.28489483 0.45729466]
 [0.88379284 0.02788566 0.46755265]]
Вектор:
[0.08929793 0.65498872 0.17663185]
Результат перемноження матриці на вектор:
[0.31570285 0.17977034]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = matrix1 * matrix2

print("Результат поелементного множення матриць:")
print(result)

Матриця 1:
[[10  8]
 [ 3  1]]
Матриця 2:
[[10  4]
 [ 4  6]]
Результат поелементного множення матриць:
[[100  32]
 [ 12   6]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(result)

Матриця 1:
[[ 3 10]
 [ 5  2]]
Матриця 2:
[[7 7]
 [1 4]]
Добуток матриць:
[[31 61]
 [37 43]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix = np.random.randint(1, 101, size=(5, 5))

print("Матриця:")
print(matrix)

sum_elements = np.sum(matrix)

print("Сума елементів матриці:")
print(sum_elements)

Матриця:
[[ 61  56   1  91  67]
 [ 64  58   7  30  71]
 [ 55  99  71  10 100]
 [ 78  36  88  39  62]
 [ 58  66  67  94  33]]
Сума елементів матриці:
1462


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

difference = matrix1 - matrix2

print("Різниця матриць:")
print(difference)

Матриця 1:
[[ 6  2  4  4]
 [ 6  4 10  2]
 [ 9  7  5  5]
 [ 6  1  3  1]]
Матриця 2:
[[ 8  6  7  1]
 [ 2  3  3  6]
 [ 5  5  4  6]
 [10  8 10  8]]
Різниця матриць:
[[-2 -4 -3  3]
 [ 4  1  7 -4]
 [ 4  2  1 -1]
 [-4 -7 -7 -7]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix = np.random.rand(3, 3)

print("Матриця:")
print(matrix)

sum_rows = np.sum(matrix, axis=1)

print("Вектор-стовпчик сум елементів кожного рядка матриці:")
print(sum_rows)

Матриця:
[[0.0332514  0.94620213 0.23793047]
 [0.48581902 0.2820644  0.22285037]
 [0.76069872 0.6083135  0.01457008]]
Вектор-стовпчик сум елементів кожного рядка матриці:
[1.21738401 0.99073379 1.38358231]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix = np.random.randint(-10, 11, size=(3, 4))

print("Матриця:")
print(matrix)

squares_matrix = matrix ** 2

print("Матриця з квадратами чисел:")
print(squares_matrix)

Матриця:
[[  5  -9   5  -2]
 [ 10   3  -6  -1]
 [  4  -6 -10   0]]
Матриця з квадратами чисел:
[[ 25  81  25   4]
 [100   9  36   1]
 [ 16  36 100   0]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector = np.random.randint(1, 51, size=4)

print("Вектор:")
print(vector)

sqrt_vector = np.sqrt(vector)

print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)

Вектор:
[20 27 49 15]
Вектор з квадратними коренями чисел:
[4.47213595 5.19615242 7.         3.87298335]
